name: getwellsoon_apk
description: A Flutter application for wellness and healthcare.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.0.0
  image_picker: ^0.8.4+4
  supabase_flutter: ^2.3.1
  shared_preferences: ^2.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/google_icon.png  # For Google login button
    - assets/icons/Logo.png         # App logo
    - assets/icons/main/
    - assets/icons/happy/
    - assets/icons/navbar/
    - assets/icons/angry/
    - assets/icons/neutral/
    - assets/icons/sad/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
